[moomoo]
[moomoo.src]
webpage = "https://www.moomoo.com/download/linux"
# HTML内の "Ver.16.1.14618" から数字だけを抽出
regex = 'Ver\.([0-9.]+)'

[moomoo.fetch]
# 特定したドメインとパスを使用
url = "https://softwaredownload.futustatic.com/moomoo_desktop_$ver_amd64.deb"