# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  moomoo = {
    pname = "moomoo";
    version = "16.14.15908";
    src = fetchurl {
      url = "https://softwaredownload.futustatic.com/moomoo_desktop_16.14.15908_amd64.deb";
      sha256 = "sha256-wEug6QgHpaBIokr1PI6hIAPMozet33qnevxDNOVDq8s=";
    };
  };
}
