# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  moomoo = {
    pname = "moomoo";
    version = "16.11.15618";
    src = fetchurl {
      url = "https://softwaredownload.futustatic.com/moomoo_desktop_16.11.15618_amd64.deb";
      sha256 = "sha256-WgMbokwqTyYoR7uEPdwy+0C6q8s7fpeGO2AaKSYNSGQ=";
    };
  };
}
