# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  moomoo = {
    pname = "moomoo";
    version = "16.30.17508";
    src = fetchurl {
      url = "https://softwaredownload.futustatic.com/moomoo_desktop_16.30.17508_amd64.deb";
      sha256 = "sha256-AjNi3M95oym/UZb5PiF6paZLxIzjBOZxbj8Juyg2ZRY=";
    };
  };
}
